### ISSUE TITLE
Epic: Project development + graphic design

### ISSUE THREAD

**Issue by keironchaudhry** [keironchaudhry/js-game-project#4]
# Project development + graphic design

**Epic Description**: Development of gaming graphic design and development for the game story + mechanics.

## Tasks

- [ ] **Graphic design**: Design and create graphic design for the gaming platform, for playable sprite, enemy sprite, engageable icons, background, obstacles and any additional ideas.
- [ ] **Story**: Develop a narrative to go along with the game.
- [ ] **Integration**: Brings these ideas into the code base - graphic designs should be placed in the assets folder and the story should be integrated into the game mechanics.

## Additional Notes

[Add any additional notes or information about the epic here.]
